#+TITLE: NFiles

NFiles is a Common Lisp library to help manage file persistence and loading, in
particular user-generated files like configuration files and cache files.

Features:

- Dynamic and customizable path expansion.
- Extensible serialization.
- Cached reads and writes.
  When a =file= object expands to the same path as another one, a =read= or
  =write= on it won't do anything in case there was no change since last write.
- On-the-fly PGP encryption.
- Profile support.
- Backup management.

# TODO: On-the-fly compression?

** Why?

When an image is generated, path expansion may already be resolved and thus
hard-coded within the image, which makes it unfit for delivery.  Consider this:

```lisp
> (defvar *foo-path* (uiop:xdg-config-home))
*FOO-PATH*
> *foo-path*
#P"/home/ambrevar/.config/"
```

Now if I ship this image to my friend Kaboom, =*foo-path*= will expand to
=#P"/home/ambrevar/.config/"= on their machine instead of the expected
=#P"/home/kaboom/.config/"=.

** Examples

# TODO: Finish!
